require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Property = require('../models/Property.model');

const sampleOwnerId = new mongoose.Types.ObjectId('6a37e0b6fcb01484cd75b7dc');

const sampleCommercials = [
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'commercial',
    purpose: 'rent',
    title: 'Grade A Tech Park Office Space in Hinjewadi',
    description: 'Fully furnished plug-and-play modern corporate office space located in Hinjewadi Phase 1. Features 60 workstations, 4 executive cabins, 2 conference rooms, high-speed fiber internet, and 100% DG power backup.',
    city: 'Pune',
    area: 'Hinjewadi',
    address: 'Embassy TechZone, Phase 1, Hinjewadi',
    fullAddress: 'Tower 3, Level 4, Embassy TechZone, Hinjewadi Phase 1, Pune 411057',
    landmark: 'Near Wipro Circle',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411057',
    latitude: 18.5912,
    longitude: 73.7389,
    location: { type: 'Point', coordinates: [73.7389, 18.5912] },
    pricing: {
      expectedPrice: 185000,
      pricePerSqFt: 65,
      securityDeposit: 550000,
      depositMonths: 3,
      maintenanceCharges: 15000,
      maintenanceType: 'monthly_fixed',
      bookingAmount: 50000,
      pricingNegotiable: true,
      camChargesPerSqFt: 8,
      dgBackupCharges: 5000,
      taxGstApplicable: true,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1000', caption: 'Modern Open Office Layout', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1000', caption: 'Executive Conference Room', isMain: false, order: 1 },
      { url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000', caption: 'Workstation Bay', isMain: false, order: 2 },
    ],
    amenities: ['Central AC', '24/7 Security', 'CCTV Surveillance', 'Power Backup', 'Cafeteria', 'Visitor Parking', 'High Speed Elevators', 'Fire Fighting System'],
    contactPhone: '9876543210',
    contactWhatsapp: '9876543210',
    contactEmail: 'commercials@pginfo.online',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    dataQualityScore: 5,
    views: 412,
    inquiries: 29,
    commercialDetails: {
      commercialSubtype: 'office_space',
      carpetAreaSqFt: 2850,
      superBuiltUpAreaSqFt: 3500,
      ceilingHeightFt: 11,
      floorNumber: 4,
      totalFloors: 12,
      passengerLifts: 4,
      goodsLifts: 1,
      fitoutStatus: 'fully_furnished_plug_and_play',
      fitoutDetails: {
        workstationsCount: 60,
        cabinsCount: 4,
        meetingRoomsCount: 2,
        conferenceRoomsCount: 1,
        receptionArea: true,
        pantryType: 'cafeteria',
        privateWashrooms: 2,
        publicWashroomsPerFloor: 4,
        centralAirConditioning: true,
      },
      powerLoadKW: 45,
      powerBackupCapacityKVA: 100,
      threePhaseConnection: true,
      coveredParkingSlots: 8,
      openParkingSlots: 4,
      buildingGrade: 'grade_a',
      fireSafetyNOC: true,
      fireSprinklersInstalled: true,
    },
  },
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'commercial',
    purpose: 'rent',
    title: 'High-Footfall Retail Showroom on Main Road Baner',
    description: 'Prominent ground-floor commercial retail showroom facing the 100ft Baner Main Road. Ideal for fashion brands, clinics, electronics, or fine-dining restaurants. Double-height frontage with excellent visibility.',
    city: 'Pune',
    area: 'Baner',
    address: 'Baner Main Road, opposite Balewadi High Street junction',
    fullAddress: 'Ground Floor, Signature Plaza, Baner Main Road, Pune 411045',
    landmark: 'Opposite Balewadi High Street',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411045',
    latitude: 18.5590,
    longitude: 73.7868,
    location: { type: 'Point', coordinates: [73.7868, 18.5590] },
    pricing: {
      expectedPrice: 120000,
      pricePerSqFt: 110,
      securityDeposit: 360000,
      depositMonths: 3,
      maintenanceCharges: 8000,
      maintenanceType: 'monthly_fixed',
      pricingNegotiable: true,
      taxGstApplicable: true,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1555529771-835f59fc5efe?w=1000', caption: 'Front Glass Elevation', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=1000', caption: 'Spacious Retail Area', isMain: false, order: 1 },
    ],
    amenities: ['Main Road Facing', 'Ample Parking', 'Power Backup', 'Water Storage', 'Private Washroom'],
    contactPhone: '9876543210',
    contactWhatsapp: '9876543210',
    contactEmail: 'commercials@pginfo.online',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    dataQualityScore: 5,
    views: 320,
    inquiries: 18,
    commercialDetails: {
      commercialSubtype: 'retail_shop',
      carpetAreaSqFt: 1100,
      superBuiltUpAreaSqFt: 1450,
      ceilingHeightFt: 14,
      entranceWidthFt: 24,
      floorNumber: 0,
      totalFloors: 5,
      fitoutStatus: 'warm_shell',
      fitoutDetails: {
        receptionArea: false,
        pantryType: 'dry',
        privateWashrooms: 1,
      },
      powerLoadKW: 20,
      threePhaseConnection: true,
      coveredParkingSlots: 2,
      openParkingSlots: 6,
      buildingGrade: 'grade_a',
      fireSafetyNOC: true,
    },
  },
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'commercial',
    purpose: 'rent',
    title: 'Boutique Co-working & Startup Hub in Wakad',
    description: 'Fully furnished flexible boutique co-working setup with high-speed WiFi, dedicated desk pods, meeting room, and unlimited beverage access.',
    city: 'Pune',
    area: 'Wakad',
    address: 'Dutta Mandir Road, Wakad',
    fullAddress: '2nd Floor, Apex Business Bay, Wakad, Pune 411057',
    landmark: 'Near Sayaji Hotel',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411057',
    latitude: 18.5987,
    longitude: 73.7621,
    location: { type: 'Point', coordinates: [73.7621, 18.5987] },
    pricing: {
      expectedPrice: 75000,
      pricePerSqFt: 50,
      securityDeposit: 150000,
      depositMonths: 2,
      maintenanceCharges: 0,
      maintenanceType: 'included',
      pricingNegotiable: false,
      taxGstApplicable: true,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1000', caption: 'Co-working Collaborative Space', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1000', caption: 'Conference & Meeting Hub', isMain: false, order: 1 },
    ],
    amenities: ['High Speed WiFi', 'Air Conditioned', 'Coffee Machine', 'Biometric Access', 'Printer Scanner', 'Power Backup'],
    contactPhone: '9876543210',
    status: 'approved',
    isVerified: true,
    commercialDetails: {
      commercialSubtype: 'co_working',
      carpetAreaSqFt: 1500,
      superBuiltUpAreaSqFt: 1850,
      floorNumber: 2,
      totalFloors: 6,
      fitoutStatus: 'fully_furnished_plug_and_play',
      fitoutDetails: {
        workstationsCount: 30,
        cabinsCount: 2,
        meetingRoomsCount: 1,
        receptionArea: true,
        pantryType: 'cafeteria',
        privateWashrooms: 2,
        centralAirConditioning: true,
      },
      powerLoadKW: 25,
      coveredParkingSlots: 3,
      buildingGrade: 'grade_b',
    },
  },
];

const sampleResidentialFlats = [
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'residential_rental',
    purpose: 'rent',
    title: 'Luxury 2 BHK Fully Furnished Flat in Wakad',
    description: 'Beautiful garden-facing 2 BHK flat in a premium gated society. Comes with modern modular kitchen, king-size beds, 55-inch smart TV, automatic washing machine, and double balconies. Ready for immediate move-in.',
    city: 'Pune',
    area: 'Wakad',
    address: 'Kaspate Vasti, Wakad',
    fullAddress: 'Tower B, Flat 704, Mont Vert Tropez, Kaspate Vasti, Wakad, Pune 411057',
    landmark: 'Behind Ginger Hotel',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411057',
    latitude: 18.5982,
    longitude: 73.7650,
    location: { type: 'Point', coordinates: [73.7650, 18.5982] },
    pricing: {
      expectedPrice: 28000,
      securityDeposit: 60000,
      depositMonths: 2,
      maintenanceCharges: 2500,
      maintenanceType: 'monthly_fixed',
      pricingNegotiable: true,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000', caption: 'Spacious Living Room', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000', caption: 'Master Bedroom with Wardrobes', isMain: false, order: 1 },
      { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1000', caption: 'Modular Kitchen with Chimney', isMain: false, order: 2 },
    ],
    amenities: ['Swimming Pool', 'Clubhouse', 'Gymnasium', 'Gated Security', 'Children Play Area', 'Power Backup', 'Covered Parking', 'Elevator'],
    contactPhone: '9876543210',
    contactWhatsapp: '9876543210',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    dataQualityScore: 5,
    views: 580,
    inquiries: 42,
    residentialDetails: {
      propertySubtype: 'apartment_flat',
      bhk: '2BHK',
      bedrooms: 2,
      bathrooms: 2,
      balconies: 2,
      carpetAreaSqFt: 880,
      superBuiltUpAreaSqFt: 1120,
      floorNumber: 7,
      totalFloors: 14,
      facing: 'East',
      furnishingStatus: 'fully_furnished',
      furnishingDetails: {
        fans: 4,
        lights: 10,
        wardrobes: 2,
        modularKitchen: true,
        geysers: 2,
        acCount: 2,
        tv: true,
        refrigerator: true,
        washingMachine: true,
        sofa: true,
        diningTable: true,
        bedsCount: 2,
        mattresses: true,
        gasPipeline: true,
      },
      reservedCoveredParking: 1,
      preferredTenants: ['family', 'bachelors_female', 'any'],
      societyName: 'Mont Vert Tropez',
      gatedSecurity: true,
      waterSupply: ['corporation', '24_7_water'],
      powerBackup: 'partial_common_areas',
    },
  },
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'residential_rental',
    purpose: 'rent',
    title: 'Spacious 3 BHK Semi-Furnished Flat in Baner',
    description: 'Contemporary 3 BHK apartment in an upscale high-rise society. Overlooks the Baner hills with cross-ventilation. Walking distance to supermarkets, top international schools, and Balewadi High Street.',
    city: 'Pune',
    area: 'Baner',
    address: 'Near Pan Card Club Road, Baner',
    fullAddress: 'Block C, 11th Floor, Skyi Songbirds, Baner, Pune 411045',
    landmark: 'Near Primrose Mall',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411045',
    latitude: 18.5580,
    longitude: 73.7910,
    location: { type: 'Point', coordinates: [73.7910, 18.5580] },
    pricing: {
      expectedPrice: 42000,
      securityDeposit: 100000,
      depositMonths: 2,
      maintenanceCharges: 3500,
      maintenanceType: 'monthly_fixed',
      pricingNegotiable: false,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000', caption: 'Sunlit Living & Dining Room', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1000', caption: 'Modern Modular Kitchen', isMain: false, order: 1 },
      { url: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1000', caption: 'Scenic Hill-View Balcony', isMain: false, order: 2 },
    ],
    amenities: ['Tennis Court', 'Infinity Pool', 'Gymnasium', 'Landscaped Garden', 'Intercom', '24/7 Security', 'Piped Gas', 'Covered Parking'],
    contactPhone: '9876543210',
    contactWhatsapp: '9876543210',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    dataQualityScore: 5,
    views: 450,
    inquiries: 31,
    residentialDetails: {
      propertySubtype: 'apartment_flat',
      bhk: '3BHK',
      bedrooms: 3,
      bathrooms: 3,
      balconies: 3,
      carpetAreaSqFt: 1450,
      superBuiltUpAreaSqFt: 1850,
      floorNumber: 11,
      totalFloors: 18,
      facing: 'North-East',
      furnishingStatus: 'semi_furnished',
      furnishingDetails: {
        fans: 6,
        lights: 14,
        wardrobes: 3,
        modularKitchen: true,
        geysers: 3,
        gasPipeline: true,
      },
      reservedCoveredParking: 2,
      preferredTenants: ['family', 'company_lease', 'any'],
      societyName: 'Skyi Songbirds',
      gatedSecurity: true,
      waterSupply: ['corporation'],
      powerBackup: 'full',
    },
  },
  {
    owner: sampleOwnerId,
    listedBy: 'owner',
    category: 'residential_rental',
    purpose: 'rent',
    title: 'Cozy 1 BHK Apartment Near IT Park Hinjewadi',
    description: 'Affordable and well-maintained 1 BHK flat perfect for bachelor IT professionals or young couples. Includes wardrobe, geyser, kitchen cabinets, and lift with power backup.',
    city: 'Pune',
    area: 'Hinjewadi',
    address: 'Maan Road, Hinjewadi Phase 1',
    fullAddress: 'Wing A, 3rd Floor, Shanti Enclave, Hinjewadi Phase 1, Pune 411057',
    landmark: 'Near Infosys Circle',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '411057',
    latitude: 18.5901,
    longitude: 73.7370,
    location: { type: 'Point', coordinates: [73.7370, 18.5901] },
    pricing: {
      expectedPrice: 15000,
      securityDeposit: 30000,
      depositMonths: 2,
      maintenanceCharges: 1000,
      maintenanceType: 'monthly_fixed',
      pricingNegotiable: true,
    },
    photos: [
      { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000', caption: 'Cozy Living Area', isMain: true, order: 0 },
      { url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=1000', caption: 'Bedroom with Attached Balcony', isMain: false, order: 1 },
    ],
    amenities: ['Lift', 'Power Backup', 'Security Guard', 'Two Wheeler Parking', 'Water Purifier'],
    contactPhone: '9876543210',
    status: 'approved',
    isVerified: true,
    residentialDetails: {
      propertySubtype: 'apartment_flat',
      bhk: '1BHK',
      bedrooms: 1,
      bathrooms: 1,
      balconies: 1,
      carpetAreaSqFt: 520,
      superBuiltUpAreaSqFt: 650,
      floorNumber: 3,
      totalFloors: 5,
      furnishingStatus: 'semi_furnished',
      furnishingDetails: {
        fans: 2,
        lights: 5,
        wardrobes: 1,
        modularKitchen: false,
        geysers: 1,
      },
      preferredTenants: ['any'],
      societyName: 'Shanti Enclave',
    },
  },
];

async function seed() {
  await connectDB();
  console.log('Connected to MongoDB for commercial & residential seeding...');

  const commCount = await Property.countDocuments({ category: 'commercial' });
  const flatCount = await Property.countDocuments({ category: 'residential_rental' });

  if (commCount === 0) {
    console.log('Seeding commercial properties...');
    await Property.insertMany(sampleCommercials);
    console.log(`Inserted ${sampleCommercials.length} commercial properties.`);
  } else {
    console.log(`Already have ${commCount} commercial properties, skipping.`);
  }

  if (flatCount === 0) {
    console.log('Seeding residential rented flats...');
    await Property.insertMany(sampleResidentialFlats);
    console.log(`Inserted ${sampleResidentialFlats.length} rented flats.`);
  } else {
    console.log(`Already have ${flatCount} residential flats, skipping.`);
  }

  await mongoose.disconnect();
  console.log('Seeding complete!');
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
